
server:
  port: 8081
  servlet:
    context-path: /pessoa

spring:
  application:
    name: pessoa
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      # dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/pessoa?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC 
    username: root
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
pessoa:
  rabbitmq:
    exchange: pessoa.exchange
    routingKey: pessoa.routingKey
    
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/registry/eureka
    